version: '3.6'

services:
  service-api:
    build:
      context: .
      dockerfile: Dockerfile-service
    container_name: coffee-chat-service-api
    image: 340651985871.dkr.ecr.ap-northeast-2.amazonaws.com/coffee-chat:1.0.1
    ports:
      - "8080:8080"
