version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD='1234'
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"

# docker exec -it postgres /bin/bash
# psql -U postgres
# create database tortee
# alter role postgres with password '1234'

