server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false  # Eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지에 대한 설정입니다.

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-api
          uri: http://localhost:8080/
          predicates:
            - Path=/api/**
        - id: external-api
          uri: http://localhost:8090/
          predicates:
              - Path=/ext/api/**



