server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true  # Eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지에 대한 설정입니다.

spring:
  application:
    name: external-api
  main:
    allow-bean-definition-overriding: true

